import React, { useState, useEffect } from 'react';

const SidebarBoxes = () => {
  const [visibleBox, setVisibleBox] = useState(null);

  // Function to handle box visibility with auto-hide after 15 seconds
  const showBox = (boxId) => {
    setVisibleBox(boxId);

    // Auto-hide box after 15 seconds
    setTimeout(() => {
      setVisibleBox(null);
    }, 15000); // 15 seconds
  };

  return (
    <div>
      {/* Overview Box */}
      {visibleBox === 'box' && (
        <div className="p-5 rounded-2xl mt-28 ml-64 bg-slate-200 text-gray-600 w-64 absolute">
          <strong>Overview</strong> <br />
          The website is a renewable energy monitoring platform that provides alerts based on companies' energy
          consumption relative to their carbon emission ratios. It aims to promote sustainable practices and support
          the green revolution by helping organizations optimize their energy use and reduce their environmental impact.
        </div>
      )}

      {/* Energy Usage Box */}
      {visibleBox === 'box1' && (
        <div className="p-5 rounded-2xl mt-28 ml-64 bg-slate-200 text-gray-600 w-64 absolute">
          <strong>Energy Usage</strong> <br />
          Energy usage refers to the total amount of energy consumed by an entity, typically measured in kilowatt-hours (kWh).
          Monitoring energy usage helps organizations identify consumption patterns, improve efficiency, and reduce costs.
          By analyzing usage data, companies can implement energy-saving measures and support sustainability initiatives.
        </div>
      )}

      {/* Carbon Offset Box */}
      {visibleBox === 'box2' && (
        <div className="p-5 rounded-2xl mt-28 ml-64 bg-slate-200 text-gray-600 w-64 absolute">
          <strong>Carbon Offset</strong> <br />
          Carbon offsetting involves compensating for carbon dioxide emissions produced by activities, such as energy
          consumption, by funding projects that reduce or capture emissions elsewhere. This could include investing in
          renewable energy sources, reforestation, or energy efficiency projects.
        </div>
      )}

      {/* Alerts Box */}
      {visibleBox === 'box3' && (
        <div className="p-5 rounded-2xl mt-28 ml-64 bg-slate-200 text-gray-600 w-64 absolute">
          <strong>Alerts</strong> <br />
          Alerts are notifications generated by the monitoring system to inform companies when their energy consumption
          exceeds predefined thresholds or when carbon emission ratios become concerning. These alerts enable proactive
          management of energy usage, encouraging timely interventions to reduce waste and lower emissions.
        </div>
      )}

      {/* Buttons to Show Boxes */}
      <div className="mt-10">
        <button onClick={() => showBox('box')} className="mr-4 p-2 bg-blue-500 text-white rounded-lg">Show Overview</button>
        <button onClick={() => showBox('box1')} className="mr-4 p-2 bg-blue-500 text-white rounded-lg">Show Energy Usage</button>
        <button onClick={() => showBox('box2')} className="mr-4 p-2 bg-blue-500 text-white rounded-lg">Show Carbon Offset</button>
        <button onClick={() => showBox('box3')} className="p-2 bg-blue-500 text-white rounded-lg">Show Alerts</button>
      </div>
    </div>
  );
};

export default SidebarBoxes;
